#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out_file="$repo_root/docs/functions.md"
tmp_file="$(mktemp)"

extract_functions() {
  local file_path="$1"
  awk '
    {
      line = $0
      sub(/#.*/, "", line)
      if (line ~ /^function[ \t]+[A-Za-z_][A-Za-z0-9_!.]*[ \t]*\(/) {
        sub(/^function[ \t]+/, "", line)
        sub(/[ \t]*\(.*/, "", line)
        print line
      } else if (line ~ /^[A-Za-z_][A-Za-z0-9_!.]*[ \t]*\(.*\)[ \t]*=[^=]/) {
        sub(/[ \t]*\(.*/, "", line)
        print line
      }
    }
  ' "$file_path" | awk '!seen[$0]++'
}

{
  echo "# Repository Function Documentation"
  echo
  echo "This document is auto-generated by \`scripts/generate_functions_doc.sh\`."
  echo
  echo "To regenerate:"
  echo
  echo "\`\`\`bash"
  echo "./scripts/generate_functions_doc.sh"
  echo "\`\`\`"
  echo

  while IFS= read -r rel_path; do
    abs_path="$repo_root/$rel_path"
    echo "## $rel_path"

    funcs="$(extract_functions "$abs_path")"
    if [[ -z "$funcs" ]]; then
      echo "- No top-level function definitions."
    else
      while IFS= read -r fn; do
        [[ -n "$fn" ]] || continue
        echo "- \`$fn(...)\`"
      done <<< "$funcs"
    fi
    echo
  done < <(cd "$repo_root" && rg --files src/code -g "*.jl" | sort)
} > "$tmp_file"

mv "$tmp_file" "$out_file"
echo "Wrote $out_file"
